### ISSUE TITLE
Error After Initial Plugin Setup

### ISSUE THREAD

**Issue by SyedUsamaHaiderKazmi** [efectn/laravel-menu-builder#9]
**Issue:** Attempt to read property ID on Null
**Exception At:** Menu::Render()

![image](https://github.com/efectn/laravel-menu-builder/assets/30346254/7958b094-7486-4c0e-bb8c-c01615bd1812)

**Comment by artifex-media** [comment]
Same issue.

**Comment by efectn** [comment]
Will check it soon

**Comment by rafig256** [comment]
After executing the necessary commands, when I open the blade page, it gives the following error:
Attempt to read property "id" on null
Apparently this is because there is no data in the database yet. I fixed this error by manually adding a data to the database. But it will be better if this error is fixed automatically.
Maybe writing a seed can completely solve this simple problem

**Comment by SyedUsamaHaiderKazmi** [comment]
> Will check it soon

Hi @efectn i hope that you and all other participants finds this in good health

I am closing this issue with a solution that i implemented within the package on my localhost. Here is the details:

In the package, originally in the **MenuBuilder@render() function:** _(at line=19)_
**File Path=** _efectn/laravel-menu-builder/src/MenuBuilder.php_

`if ((request()->has("action") && empty(request()->input("menu"))) || request()->input("menu") == '0') {
            return view('menu-builder::menu-html')->with("menulist" , $menuList);
        }`

Based on validation above, 

- if request has action and the **menu** (which is expected as selected menu) is empty
- Or against menu key, value is equal to 0 within the request 

then return view with empty values and allow user to create menu, but when the package is freshly installed, none of the validation meets and system goes to next if which tries to get the very first menu from the database table, which in reality is empty.

After carefully debugging it (atleast based on my scenario), i added a validation within the validation mentioned above, which also checks the null value.

**Updated validation:**

`if ((request()->has("action") && (empty(request()->input("menu")) || is_null(request()->input("menu")))) || (request()->input("menu") == '0' || request()->input("menu") == null)) {
            return view('menu-builder::menu-html')->with("menulist" , $menuList);
        }`

@efectn if you add this within the package and update the package, i hope it will help many new package users who are looking forward to try this awesome package!

**Comment by efectn** [comment]
Hi @SyedUsamaHaiderKazmi would you like to create PR for your fix? I'm so busy with other projects and i couldn't maintain this repo and so sorry about that. I will try to fix this issues weekend and perhaps refactor the ui of the extension next weeks

**Comment by SyedUsamaHaiderKazmi** [comment]
Hi @efectn sure, i can do that, and will do it this weekend.

**Comment by artifex-media** [comment]
This issue not closed as it's still present on a fresh install. You indeed have to enter data in the database manually in order to stop the error.
A seeder with an example menu would also be usefull.

Let us know if you need any help with the repo :)
